---
listen:
  host: 10.30.50.78
  port: 55758
mysql:
  db: attendance
  host: 10.30.50.70
  port: 3306
  user: attendance
  pass: 8tcDCn9FKiZcrWXFQ5gm
redis:
  host: 10.30.50.71
  port: 6379
  db: 8
  pass: 3D6kiP36dYTK9X2a
logfile: attendance.log