---
listen:
  host: localhost
  port: 55758
mysql:
  db: attendance
  host: localhost
  port: 3306
  user: attendance
  pass: 8tcDCn9FKiZcrWXFQ5gm
redis:
  host: localhost
  port: 6379
  db: 8
  pass: pFG64SBbhGB56K8Cv5eZbrdQ
logfile: attendance.log
