---
listen:
  host: localhost
  port: 5578
mysql:
  db: attendance
  host: localhost
  port: 3306
  user: attendance
  pass: 8tcDCn9FKiZcrWXFQ5gm
redis:
  host: localhost
  port: 6379
  db: 8
  pass: 3D6kiP36dYTK9X2a
logfile: attendance-prod.log