version: "3.8"
services:
  mysql:
    hostname: "mysql"
    container_name: mysql
    image: mysql:5.7
    expose: 
    - "3306"
    ports:
    - "53306:3306"
    volumes:
    # mysql data volume
    - /data/mysql/data:/var/lib/mysql
    # init sql
    - /data/mysql/init:/docker-entrypoint-initdb.d
    # mysql conf dir
    - /data/mysql/conf:/etc/mysql/conf.d
    env_file:
    - ./secrets.env
    networks:
      vlan0:
        ipv4_address: 10.30.50.70
  redis:
    hostname: "redis"
    container_name: redis
    image: redis:6.0
    volumes:
    - /data/redis/data:/data
    - /data/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    expose:
    - "6379"
    ports:
    - "56379:6379"
    networks:
      vlan0:
        ipv4_address: 10.30.50.71
networks:
  vlan0:
    name: vlan0
    ipam:
      driver: default
      config:
      - subnet: "10.30.50.0/24"
