version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    expose: 
    - "3306"
    ports:
    - "53306:3306"
    volumes:
    - /home/pluto/git-base-02/attendance/mysql/data:/var/lib/mysql
    # init sql
    - /home/pluto/git-base-02/attendance/mysql/init:/docker-entrypoint-initdb.d
    - /home/pluto/git-base-02/attendance/mysql/conf:/etc/mysql/conf.d
    env_file:
    - ./secrets.env
    networks:
      v1test:
        ipv4_address: 10.30.50.70
networks:
  v1test:
    name: v1test
    ipam:
      driver: default
      config:
      - subnet: "10.30.50.0/24"
